services:
  postgres:
    image: postgres:16
    container_name: novelwebsite_dev_psql
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: novelwebsite_dev_db
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d novelwebsite_dev_db"]
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 10s
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Web Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6380:6379"

volumes:
  postgres_data:
  minio_data:
