/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RateLimitRouteImport } from './routes/rate-limit'
import { Route as UsersRouteRouteImport } from './routes/users/route'
import { Route as NovelsRouteRouteImport } from './routes/novels/route'
import { Route as AuthorsRouteRouteImport } from './routes/authors/route'
import { Route as AnnouncementsRouteRouteImport } from './routes/announcements/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as NovelsIndexRouteImport } from './routes/novels/index'
import { Route as AuthorsIndexRouteImport } from './routes/authors/index'
import { Route as NovelsCreateRouteImport } from './routes/novels_/create'
import { Route as AuthorsCreateRouteImport } from './routes/authors_/create'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as UsersUsernameIndexRouteImport } from './routes/users_/$username/index'
import { Route as AuthorsAuthorIdIndexRouteImport } from './routes/authors_/$authorId/index'
import { Route as NovelsNovelIdSlugIndexRouteImport } from './routes/novels_/$novelId_/$slug/index'
import { Route as NovelsNovelIdSlugChaptersRouteRouteImport } from './routes/novels_/$novelId_/$slug/chapters/route'
import { Route as NovelsNovelIdSlugChaptersIndexRouteImport } from './routes/novels_/$novelId_/$slug/chapters/index'
import { Route as NovelsNovelIdSlugChaptersCreateRouteImport } from './routes/novels_/$novelId_/$slug/chapters_/create'
import { Route as NovelsNovelIdSlugChaptersChapterNumberIndexRouteImport } from './routes/novels_/$novelId_/$slug/chapters_/$chapterNumber/index'
import { Route as NovelsNovelIdSlugChaptersChapterNumberEditRouteImport } from './routes/novels_/$novelId_/$slug/chapters_/$chapterNumber/edit'

const RateLimitRoute = RateLimitRouteImport.update({
  id: '/rate-limit',
  path: '/rate-limit',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRouteRoute = UsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const NovelsRouteRoute = NovelsRouteRouteImport.update({
  id: '/novels',
  path: '/novels',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsRouteRoute = AuthorsRouteRouteImport.update({
  id: '/authors',
  path: '/authors',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRouteRoute = AnnouncementsRouteRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersRouteRoute,
} as any)
const NovelsIndexRoute = NovelsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NovelsRouteRoute,
} as any)
const AuthorsIndexRoute = AuthorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthorsRouteRoute,
} as any)
const NovelsCreateRoute = NovelsCreateRouteImport.update({
  id: '/novels_/create',
  path: '/novels/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsCreateRoute = AuthorsCreateRouteImport.update({
  id: '/authors_/create',
  path: '/authors/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUsernameIndexRoute = UsersUsernameIndexRouteImport.update({
  id: '/users_/$username/',
  path: '/users/$username/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsAuthorIdIndexRoute = AuthorsAuthorIdIndexRouteImport.update({
  id: '/authors_/$authorId/',
  path: '/authors/$authorId/',
  getParentRoute: () => rootRouteImport,
} as any)
const NovelsNovelIdSlugIndexRoute = NovelsNovelIdSlugIndexRouteImport.update({
  id: '/novels_/$novelId_/$slug/',
  path: '/novels/$novelId/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const NovelsNovelIdSlugChaptersRouteRoute =
  NovelsNovelIdSlugChaptersRouteRouteImport.update({
    id: '/novels_/$novelId_/$slug/chapters',
    path: '/novels/$novelId/$slug/chapters',
    getParentRoute: () => rootRouteImport,
  } as any)
const NovelsNovelIdSlugChaptersIndexRoute =
  NovelsNovelIdSlugChaptersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => NovelsNovelIdSlugChaptersRouteRoute,
  } as any)
const NovelsNovelIdSlugChaptersCreateRoute =
  NovelsNovelIdSlugChaptersCreateRouteImport.update({
    id: '/novels_/$novelId_/$slug/chapters_/create',
    path: '/novels/$novelId/$slug/chapters/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const NovelsNovelIdSlugChaptersChapterNumberIndexRoute =
  NovelsNovelIdSlugChaptersChapterNumberIndexRouteImport.update({
    id: '/novels_/$novelId_/$slug/chapters_/$chapterNumber/',
    path: '/novels/$novelId/$slug/chapters/$chapterNumber/',
    getParentRoute: () => rootRouteImport,
  } as any)
const NovelsNovelIdSlugChaptersChapterNumberEditRoute =
  NovelsNovelIdSlugChaptersChapterNumberEditRouteImport.update({
    id: '/novels_/$novelId_/$slug/chapters_/$chapterNumber/edit',
    path: '/novels/$novelId/$slug/chapters/$chapterNumber/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRouteRoute
  '/authors': typeof AuthorsRouteRouteWithChildren
  '/novels': typeof NovelsRouteRouteWithChildren
  '/users': typeof UsersRouteRouteWithChildren
  '/rate-limit': typeof RateLimitRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/authors/create': typeof AuthorsCreateRoute
  '/novels/create': typeof NovelsCreateRoute
  '/authors/': typeof AuthorsIndexRoute
  '/novels/': typeof NovelsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/authors/$authorId/': typeof AuthorsAuthorIdIndexRoute
  '/users/$username/': typeof UsersUsernameIndexRoute
  '/novels/$novelId/$slug/chapters': typeof NovelsNovelIdSlugChaptersRouteRouteWithChildren
  '/novels/$novelId/$slug/': typeof NovelsNovelIdSlugIndexRoute
  '/novels/$novelId/$slug/chapters/create': typeof NovelsNovelIdSlugChaptersCreateRoute
  '/novels/$novelId/$slug/chapters/': typeof NovelsNovelIdSlugChaptersIndexRoute
  '/novels/$novelId/$slug/chapters/$chapterNumber/edit': typeof NovelsNovelIdSlugChaptersChapterNumberEditRoute
  '/novels/$novelId/$slug/chapters/$chapterNumber/': typeof NovelsNovelIdSlugChaptersChapterNumberIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRouteRoute
  '/rate-limit': typeof RateLimitRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/authors/create': typeof AuthorsCreateRoute
  '/novels/create': typeof NovelsCreateRoute
  '/authors': typeof AuthorsIndexRoute
  '/novels': typeof NovelsIndexRoute
  '/users': typeof UsersIndexRoute
  '/authors/$authorId': typeof AuthorsAuthorIdIndexRoute
  '/users/$username': typeof UsersUsernameIndexRoute
  '/novels/$novelId/$slug': typeof NovelsNovelIdSlugIndexRoute
  '/novels/$novelId/$slug/chapters/create': typeof NovelsNovelIdSlugChaptersCreateRoute
  '/novels/$novelId/$slug/chapters': typeof NovelsNovelIdSlugChaptersIndexRoute
  '/novels/$novelId/$slug/chapters/$chapterNumber/edit': typeof NovelsNovelIdSlugChaptersChapterNumberEditRoute
  '/novels/$novelId/$slug/chapters/$chapterNumber': typeof NovelsNovelIdSlugChaptersChapterNumberIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRouteRoute
  '/authors': typeof AuthorsRouteRouteWithChildren
  '/novels': typeof NovelsRouteRouteWithChildren
  '/users': typeof UsersRouteRouteWithChildren
  '/rate-limit': typeof RateLimitRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/authors_/create': typeof AuthorsCreateRoute
  '/novels_/create': typeof NovelsCreateRoute
  '/authors/': typeof AuthorsIndexRoute
  '/novels/': typeof NovelsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/authors_/$authorId/': typeof AuthorsAuthorIdIndexRoute
  '/users_/$username/': typeof UsersUsernameIndexRoute
  '/novels_/$novelId_/$slug/chapters': typeof NovelsNovelIdSlugChaptersRouteRouteWithChildren
  '/novels_/$novelId_/$slug/': typeof NovelsNovelIdSlugIndexRoute
  '/novels_/$novelId_/$slug/chapters_/create': typeof NovelsNovelIdSlugChaptersCreateRoute
  '/novels_/$novelId_/$slug/chapters/': typeof NovelsNovelIdSlugChaptersIndexRoute
  '/novels_/$novelId_/$slug/chapters_/$chapterNumber/edit': typeof NovelsNovelIdSlugChaptersChapterNumberEditRoute
  '/novels_/$novelId_/$slug/chapters_/$chapterNumber/': typeof NovelsNovelIdSlugChaptersChapterNumberIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/announcements'
    | '/authors'
    | '/novels'
    | '/users'
    | '/rate-limit'
    | '/auth/callback'
    | '/authors/create'
    | '/novels/create'
    | '/authors/'
    | '/novels/'
    | '/users/'
    | '/authors/$authorId/'
    | '/users/$username/'
    | '/novels/$novelId/$slug/chapters'
    | '/novels/$novelId/$slug/'
    | '/novels/$novelId/$slug/chapters/create'
    | '/novels/$novelId/$slug/chapters/'
    | '/novels/$novelId/$slug/chapters/$chapterNumber/edit'
    | '/novels/$novelId/$slug/chapters/$chapterNumber/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/announcements'
    | '/rate-limit'
    | '/auth/callback'
    | '/authors/create'
    | '/novels/create'
    | '/authors'
    | '/novels'
    | '/users'
    | '/authors/$authorId'
    | '/users/$username'
    | '/novels/$novelId/$slug'
    | '/novels/$novelId/$slug/chapters/create'
    | '/novels/$novelId/$slug/chapters'
    | '/novels/$novelId/$slug/chapters/$chapterNumber/edit'
    | '/novels/$novelId/$slug/chapters/$chapterNumber'
  id:
    | '__root__'
    | '/'
    | '/announcements'
    | '/authors'
    | '/novels'
    | '/users'
    | '/rate-limit'
    | '/auth/callback'
    | '/authors_/create'
    | '/novels_/create'
    | '/authors/'
    | '/novels/'
    | '/users/'
    | '/authors_/$authorId/'
    | '/users_/$username/'
    | '/novels_/$novelId_/$slug/chapters'
    | '/novels_/$novelId_/$slug/'
    | '/novels_/$novelId_/$slug/chapters_/create'
    | '/novels_/$novelId_/$slug/chapters/'
    | '/novels_/$novelId_/$slug/chapters_/$chapterNumber/edit'
    | '/novels_/$novelId_/$slug/chapters_/$chapterNumber/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnnouncementsRouteRoute: typeof AnnouncementsRouteRoute
  AuthorsRouteRoute: typeof AuthorsRouteRouteWithChildren
  NovelsRouteRoute: typeof NovelsRouteRouteWithChildren
  UsersRouteRoute: typeof UsersRouteRouteWithChildren
  RateLimitRoute: typeof RateLimitRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthorsCreateRoute: typeof AuthorsCreateRoute
  NovelsCreateRoute: typeof NovelsCreateRoute
  AuthorsAuthorIdIndexRoute: typeof AuthorsAuthorIdIndexRoute
  UsersUsernameIndexRoute: typeof UsersUsernameIndexRoute
  NovelsNovelIdSlugChaptersRouteRoute: typeof NovelsNovelIdSlugChaptersRouteRouteWithChildren
  NovelsNovelIdSlugIndexRoute: typeof NovelsNovelIdSlugIndexRoute
  NovelsNovelIdSlugChaptersCreateRoute: typeof NovelsNovelIdSlugChaptersCreateRoute
  NovelsNovelIdSlugChaptersChapterNumberEditRoute: typeof NovelsNovelIdSlugChaptersChapterNumberEditRoute
  NovelsNovelIdSlugChaptersChapterNumberIndexRoute: typeof NovelsNovelIdSlugChaptersChapterNumberIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rate-limit': {
      id: '/rate-limit'
      path: '/rate-limit'
      fullPath: '/rate-limit'
      preLoaderRoute: typeof RateLimitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novels': {
      id: '/novels'
      path: '/novels'
      fullPath: '/novels'
      preLoaderRoute: typeof NovelsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors': {
      id: '/authors'
      path: '/authors'
      fullPath: '/authors'
      preLoaderRoute: typeof AuthorsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof UsersRouteRoute
    }
    '/novels/': {
      id: '/novels/'
      path: '/'
      fullPath: '/novels/'
      preLoaderRoute: typeof NovelsIndexRouteImport
      parentRoute: typeof NovelsRouteRoute
    }
    '/authors/': {
      id: '/authors/'
      path: '/'
      fullPath: '/authors/'
      preLoaderRoute: typeof AuthorsIndexRouteImport
      parentRoute: typeof AuthorsRouteRoute
    }
    '/novels_/create': {
      id: '/novels_/create'
      path: '/novels/create'
      fullPath: '/novels/create'
      preLoaderRoute: typeof NovelsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors_/create': {
      id: '/authors_/create'
      path: '/authors/create'
      fullPath: '/authors/create'
      preLoaderRoute: typeof AuthorsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users_/$username/': {
      id: '/users_/$username/'
      path: '/users/$username'
      fullPath: '/users/$username/'
      preLoaderRoute: typeof UsersUsernameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors_/$authorId/': {
      id: '/authors_/$authorId/'
      path: '/authors/$authorId'
      fullPath: '/authors/$authorId/'
      preLoaderRoute: typeof AuthorsAuthorIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novels_/$novelId_/$slug/': {
      id: '/novels_/$novelId_/$slug/'
      path: '/novels/$novelId/$slug'
      fullPath: '/novels/$novelId/$slug/'
      preLoaderRoute: typeof NovelsNovelIdSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novels_/$novelId_/$slug/chapters': {
      id: '/novels_/$novelId_/$slug/chapters'
      path: '/novels/$novelId/$slug/chapters'
      fullPath: '/novels/$novelId/$slug/chapters'
      preLoaderRoute: typeof NovelsNovelIdSlugChaptersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novels_/$novelId_/$slug/chapters/': {
      id: '/novels_/$novelId_/$slug/chapters/'
      path: '/'
      fullPath: '/novels/$novelId/$slug/chapters/'
      preLoaderRoute: typeof NovelsNovelIdSlugChaptersIndexRouteImport
      parentRoute: typeof NovelsNovelIdSlugChaptersRouteRoute
    }
    '/novels_/$novelId_/$slug/chapters_/create': {
      id: '/novels_/$novelId_/$slug/chapters_/create'
      path: '/novels/$novelId/$slug/chapters/create'
      fullPath: '/novels/$novelId/$slug/chapters/create'
      preLoaderRoute: typeof NovelsNovelIdSlugChaptersCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novels_/$novelId_/$slug/chapters_/$chapterNumber/': {
      id: '/novels_/$novelId_/$slug/chapters_/$chapterNumber/'
      path: '/novels/$novelId/$slug/chapters/$chapterNumber'
      fullPath: '/novels/$novelId/$slug/chapters/$chapterNumber/'
      preLoaderRoute: typeof NovelsNovelIdSlugChaptersChapterNumberIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novels_/$novelId_/$slug/chapters_/$chapterNumber/edit': {
      id: '/novels_/$novelId_/$slug/chapters_/$chapterNumber/edit'
      path: '/novels/$novelId/$slug/chapters/$chapterNumber/edit'
      fullPath: '/novels/$novelId/$slug/chapters/$chapterNumber/edit'
      preLoaderRoute: typeof NovelsNovelIdSlugChaptersChapterNumberEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthorsRouteRouteChildren {
  AuthorsIndexRoute: typeof AuthorsIndexRoute
}

const AuthorsRouteRouteChildren: AuthorsRouteRouteChildren = {
  AuthorsIndexRoute: AuthorsIndexRoute,
}

const AuthorsRouteRouteWithChildren = AuthorsRouteRoute._addFileChildren(
  AuthorsRouteRouteChildren,
)

interface NovelsRouteRouteChildren {
  NovelsIndexRoute: typeof NovelsIndexRoute
}

const NovelsRouteRouteChildren: NovelsRouteRouteChildren = {
  NovelsIndexRoute: NovelsIndexRoute,
}

const NovelsRouteRouteWithChildren = NovelsRouteRoute._addFileChildren(
  NovelsRouteRouteChildren,
)

interface UsersRouteRouteChildren {
  UsersIndexRoute: typeof UsersIndexRoute
}

const UsersRouteRouteChildren: UsersRouteRouteChildren = {
  UsersIndexRoute: UsersIndexRoute,
}

const UsersRouteRouteWithChildren = UsersRouteRoute._addFileChildren(
  UsersRouteRouteChildren,
)

interface NovelsNovelIdSlugChaptersRouteRouteChildren {
  NovelsNovelIdSlugChaptersIndexRoute: typeof NovelsNovelIdSlugChaptersIndexRoute
}

const NovelsNovelIdSlugChaptersRouteRouteChildren: NovelsNovelIdSlugChaptersRouteRouteChildren =
  {
    NovelsNovelIdSlugChaptersIndexRoute: NovelsNovelIdSlugChaptersIndexRoute,
  }

const NovelsNovelIdSlugChaptersRouteRouteWithChildren =
  NovelsNovelIdSlugChaptersRouteRoute._addFileChildren(
    NovelsNovelIdSlugChaptersRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnnouncementsRouteRoute: AnnouncementsRouteRoute,
  AuthorsRouteRoute: AuthorsRouteRouteWithChildren,
  NovelsRouteRoute: NovelsRouteRouteWithChildren,
  UsersRouteRoute: UsersRouteRouteWithChildren,
  RateLimitRoute: RateLimitRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthorsCreateRoute: AuthorsCreateRoute,
  NovelsCreateRoute: NovelsCreateRoute,
  AuthorsAuthorIdIndexRoute: AuthorsAuthorIdIndexRoute,
  UsersUsernameIndexRoute: UsersUsernameIndexRoute,
  NovelsNovelIdSlugChaptersRouteRoute:
    NovelsNovelIdSlugChaptersRouteRouteWithChildren,
  NovelsNovelIdSlugIndexRoute: NovelsNovelIdSlugIndexRoute,
  NovelsNovelIdSlugChaptersCreateRoute: NovelsNovelIdSlugChaptersCreateRoute,
  NovelsNovelIdSlugChaptersChapterNumberEditRoute:
    NovelsNovelIdSlugChaptersChapterNumberEditRoute,
  NovelsNovelIdSlugChaptersChapterNumberIndexRoute:
    NovelsNovelIdSlugChaptersChapterNumberIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
