/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RateLimitRouteImport } from './routes/rate-limit'
import { Route as UsersRouteRouteImport } from './routes/users/route'
import { Route as NovelsRouteRouteImport } from './routes/novels/route'
import { Route as AuthorsRouteRouteImport } from './routes/authors/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as NovelsIndexRouteImport } from './routes/novels/index'
import { Route as AuthorsIndexRouteImport } from './routes/authors/index'
import { Route as NovelsCreateRouteImport } from './routes/novels_/create'
import { Route as AuthorsCreateRouteImport } from './routes/authors_/create'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as UsersUsernameIndexRouteImport } from './routes/users_/$username/index'
import { Route as NovelsNovelIdIndexRouteImport } from './routes/novels_/$novelId/index'
import { Route as AuthorsAuthorIdIndexRouteImport } from './routes/authors_/$authorId/index'
import { Route as NovelsNovelIdChaptersRouteRouteImport } from './routes/novels_/$novelId/chapters/route'
import { Route as NovelsNovelIdChaptersIndexRouteImport } from './routes/novels_/$novelId/chapters/index'
import { Route as NovelsNovelIdChaptersCreateRouteImport } from './routes/novels_/$novelId/chapters_/create'
import { Route as NovelsNovelIdChaptersChapterIdIndexRouteImport } from './routes/novels_/$novelId/chapters_/$chapterId/index'
import { Route as NovelsNovelIdChaptersChapterIdEditRouteImport } from './routes/novels_/$novelId/chapters_/$chapterId/edit'

const RateLimitRoute = RateLimitRouteImport.update({
  id: '/rate-limit',
  path: '/rate-limit',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRouteRoute = UsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const NovelsRouteRoute = NovelsRouteRouteImport.update({
  id: '/novels',
  path: '/novels',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsRouteRoute = AuthorsRouteRouteImport.update({
  id: '/authors',
  path: '/authors',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersRouteRoute,
} as any)
const NovelsIndexRoute = NovelsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NovelsRouteRoute,
} as any)
const AuthorsIndexRoute = AuthorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthorsRouteRoute,
} as any)
const NovelsCreateRoute = NovelsCreateRouteImport.update({
  id: '/novels_/create',
  path: '/novels/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsCreateRoute = AuthorsCreateRouteImport.update({
  id: '/authors_/create',
  path: '/authors/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUsernameIndexRoute = UsersUsernameIndexRouteImport.update({
  id: '/users_/$username/',
  path: '/users/$username/',
  getParentRoute: () => rootRouteImport,
} as any)
const NovelsNovelIdIndexRoute = NovelsNovelIdIndexRouteImport.update({
  id: '/novels_/$novelId/',
  path: '/novels/$novelId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsAuthorIdIndexRoute = AuthorsAuthorIdIndexRouteImport.update({
  id: '/authors_/$authorId/',
  path: '/authors/$authorId/',
  getParentRoute: () => rootRouteImport,
} as any)
const NovelsNovelIdChaptersRouteRoute =
  NovelsNovelIdChaptersRouteRouteImport.update({
    id: '/novels_/$novelId/chapters',
    path: '/novels/$novelId/chapters',
    getParentRoute: () => rootRouteImport,
  } as any)
const NovelsNovelIdChaptersIndexRoute =
  NovelsNovelIdChaptersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => NovelsNovelIdChaptersRouteRoute,
  } as any)
const NovelsNovelIdChaptersCreateRoute =
  NovelsNovelIdChaptersCreateRouteImport.update({
    id: '/novels_/$novelId/chapters_/create',
    path: '/novels/$novelId/chapters/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const NovelsNovelIdChaptersChapterIdIndexRoute =
  NovelsNovelIdChaptersChapterIdIndexRouteImport.update({
    id: '/novels_/$novelId/chapters_/$chapterId/',
    path: '/novels/$novelId/chapters/$chapterId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const NovelsNovelIdChaptersChapterIdEditRoute =
  NovelsNovelIdChaptersChapterIdEditRouteImport.update({
    id: '/novels_/$novelId/chapters_/$chapterId/edit',
    path: '/novels/$novelId/chapters/$chapterId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authors': typeof AuthorsRouteRouteWithChildren
  '/novels': typeof NovelsRouteRouteWithChildren
  '/users': typeof UsersRouteRouteWithChildren
  '/rate-limit': typeof RateLimitRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/authors/create': typeof AuthorsCreateRoute
  '/novels/create': typeof NovelsCreateRoute
  '/authors/': typeof AuthorsIndexRoute
  '/novels/': typeof NovelsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/novels/$novelId/chapters': typeof NovelsNovelIdChaptersRouteRouteWithChildren
  '/authors/$authorId/': typeof AuthorsAuthorIdIndexRoute
  '/novels/$novelId/': typeof NovelsNovelIdIndexRoute
  '/users/$username/': typeof UsersUsernameIndexRoute
  '/novels/$novelId/chapters/create': typeof NovelsNovelIdChaptersCreateRoute
  '/novels/$novelId/chapters/': typeof NovelsNovelIdChaptersIndexRoute
  '/novels/$novelId/chapters/$chapterId/edit': typeof NovelsNovelIdChaptersChapterIdEditRoute
  '/novels/$novelId/chapters/$chapterId/': typeof NovelsNovelIdChaptersChapterIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rate-limit': typeof RateLimitRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/authors/create': typeof AuthorsCreateRoute
  '/novels/create': typeof NovelsCreateRoute
  '/authors': typeof AuthorsIndexRoute
  '/novels': typeof NovelsIndexRoute
  '/users': typeof UsersIndexRoute
  '/authors/$authorId': typeof AuthorsAuthorIdIndexRoute
  '/novels/$novelId': typeof NovelsNovelIdIndexRoute
  '/users/$username': typeof UsersUsernameIndexRoute
  '/novels/$novelId/chapters/create': typeof NovelsNovelIdChaptersCreateRoute
  '/novels/$novelId/chapters': typeof NovelsNovelIdChaptersIndexRoute
  '/novels/$novelId/chapters/$chapterId/edit': typeof NovelsNovelIdChaptersChapterIdEditRoute
  '/novels/$novelId/chapters/$chapterId': typeof NovelsNovelIdChaptersChapterIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/authors': typeof AuthorsRouteRouteWithChildren
  '/novels': typeof NovelsRouteRouteWithChildren
  '/users': typeof UsersRouteRouteWithChildren
  '/rate-limit': typeof RateLimitRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/authors_/create': typeof AuthorsCreateRoute
  '/novels_/create': typeof NovelsCreateRoute
  '/authors/': typeof AuthorsIndexRoute
  '/novels/': typeof NovelsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/novels_/$novelId/chapters': typeof NovelsNovelIdChaptersRouteRouteWithChildren
  '/authors_/$authorId/': typeof AuthorsAuthorIdIndexRoute
  '/novels_/$novelId/': typeof NovelsNovelIdIndexRoute
  '/users_/$username/': typeof UsersUsernameIndexRoute
  '/novels_/$novelId/chapters_/create': typeof NovelsNovelIdChaptersCreateRoute
  '/novels_/$novelId/chapters/': typeof NovelsNovelIdChaptersIndexRoute
  '/novels_/$novelId/chapters_/$chapterId/edit': typeof NovelsNovelIdChaptersChapterIdEditRoute
  '/novels_/$novelId/chapters_/$chapterId/': typeof NovelsNovelIdChaptersChapterIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authors'
    | '/novels'
    | '/users'
    | '/rate-limit'
    | '/auth/callback'
    | '/authors/create'
    | '/novels/create'
    | '/authors/'
    | '/novels/'
    | '/users/'
    | '/novels/$novelId/chapters'
    | '/authors/$authorId/'
    | '/novels/$novelId/'
    | '/users/$username/'
    | '/novels/$novelId/chapters/create'
    | '/novels/$novelId/chapters/'
    | '/novels/$novelId/chapters/$chapterId/edit'
    | '/novels/$novelId/chapters/$chapterId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/rate-limit'
    | '/auth/callback'
    | '/authors/create'
    | '/novels/create'
    | '/authors'
    | '/novels'
    | '/users'
    | '/authors/$authorId'
    | '/novels/$novelId'
    | '/users/$username'
    | '/novels/$novelId/chapters/create'
    | '/novels/$novelId/chapters'
    | '/novels/$novelId/chapters/$chapterId/edit'
    | '/novels/$novelId/chapters/$chapterId'
  id:
    | '__root__'
    | '/'
    | '/authors'
    | '/novels'
    | '/users'
    | '/rate-limit'
    | '/auth/callback'
    | '/authors_/create'
    | '/novels_/create'
    | '/authors/'
    | '/novels/'
    | '/users/'
    | '/novels_/$novelId/chapters'
    | '/authors_/$authorId/'
    | '/novels_/$novelId/'
    | '/users_/$username/'
    | '/novels_/$novelId/chapters_/create'
    | '/novels_/$novelId/chapters/'
    | '/novels_/$novelId/chapters_/$chapterId/edit'
    | '/novels_/$novelId/chapters_/$chapterId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthorsRouteRoute: typeof AuthorsRouteRouteWithChildren
  NovelsRouteRoute: typeof NovelsRouteRouteWithChildren
  UsersRouteRoute: typeof UsersRouteRouteWithChildren
  RateLimitRoute: typeof RateLimitRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthorsCreateRoute: typeof AuthorsCreateRoute
  NovelsCreateRoute: typeof NovelsCreateRoute
  NovelsNovelIdChaptersRouteRoute: typeof NovelsNovelIdChaptersRouteRouteWithChildren
  AuthorsAuthorIdIndexRoute: typeof AuthorsAuthorIdIndexRoute
  NovelsNovelIdIndexRoute: typeof NovelsNovelIdIndexRoute
  UsersUsernameIndexRoute: typeof UsersUsernameIndexRoute
  NovelsNovelIdChaptersCreateRoute: typeof NovelsNovelIdChaptersCreateRoute
  NovelsNovelIdChaptersChapterIdEditRoute: typeof NovelsNovelIdChaptersChapterIdEditRoute
  NovelsNovelIdChaptersChapterIdIndexRoute: typeof NovelsNovelIdChaptersChapterIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rate-limit': {
      id: '/rate-limit'
      path: '/rate-limit'
      fullPath: '/rate-limit'
      preLoaderRoute: typeof RateLimitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novels': {
      id: '/novels'
      path: '/novels'
      fullPath: '/novels'
      preLoaderRoute: typeof NovelsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors': {
      id: '/authors'
      path: '/authors'
      fullPath: '/authors'
      preLoaderRoute: typeof AuthorsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof UsersRouteRoute
    }
    '/novels/': {
      id: '/novels/'
      path: '/'
      fullPath: '/novels/'
      preLoaderRoute: typeof NovelsIndexRouteImport
      parentRoute: typeof NovelsRouteRoute
    }
    '/authors/': {
      id: '/authors/'
      path: '/'
      fullPath: '/authors/'
      preLoaderRoute: typeof AuthorsIndexRouteImport
      parentRoute: typeof AuthorsRouteRoute
    }
    '/novels_/create': {
      id: '/novels_/create'
      path: '/novels/create'
      fullPath: '/novels/create'
      preLoaderRoute: typeof NovelsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors_/create': {
      id: '/authors_/create'
      path: '/authors/create'
      fullPath: '/authors/create'
      preLoaderRoute: typeof AuthorsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users_/$username/': {
      id: '/users_/$username/'
      path: '/users/$username'
      fullPath: '/users/$username/'
      preLoaderRoute: typeof UsersUsernameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novels_/$novelId/': {
      id: '/novels_/$novelId/'
      path: '/novels/$novelId'
      fullPath: '/novels/$novelId/'
      preLoaderRoute: typeof NovelsNovelIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors_/$authorId/': {
      id: '/authors_/$authorId/'
      path: '/authors/$authorId'
      fullPath: '/authors/$authorId/'
      preLoaderRoute: typeof AuthorsAuthorIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novels_/$novelId/chapters': {
      id: '/novels_/$novelId/chapters'
      path: '/novels/$novelId/chapters'
      fullPath: '/novels/$novelId/chapters'
      preLoaderRoute: typeof NovelsNovelIdChaptersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novels_/$novelId/chapters/': {
      id: '/novels_/$novelId/chapters/'
      path: '/'
      fullPath: '/novels/$novelId/chapters/'
      preLoaderRoute: typeof NovelsNovelIdChaptersIndexRouteImport
      parentRoute: typeof NovelsNovelIdChaptersRouteRoute
    }
    '/novels_/$novelId/chapters_/create': {
      id: '/novels_/$novelId/chapters_/create'
      path: '/novels/$novelId/chapters/create'
      fullPath: '/novels/$novelId/chapters/create'
      preLoaderRoute: typeof NovelsNovelIdChaptersCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novels_/$novelId/chapters_/$chapterId/': {
      id: '/novels_/$novelId/chapters_/$chapterId/'
      path: '/novels/$novelId/chapters/$chapterId'
      fullPath: '/novels/$novelId/chapters/$chapterId/'
      preLoaderRoute: typeof NovelsNovelIdChaptersChapterIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novels_/$novelId/chapters_/$chapterId/edit': {
      id: '/novels_/$novelId/chapters_/$chapterId/edit'
      path: '/novels/$novelId/chapters/$chapterId/edit'
      fullPath: '/novels/$novelId/chapters/$chapterId/edit'
      preLoaderRoute: typeof NovelsNovelIdChaptersChapterIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthorsRouteRouteChildren {
  AuthorsIndexRoute: typeof AuthorsIndexRoute
}

const AuthorsRouteRouteChildren: AuthorsRouteRouteChildren = {
  AuthorsIndexRoute: AuthorsIndexRoute,
}

const AuthorsRouteRouteWithChildren = AuthorsRouteRoute._addFileChildren(
  AuthorsRouteRouteChildren,
)

interface NovelsRouteRouteChildren {
  NovelsIndexRoute: typeof NovelsIndexRoute
}

const NovelsRouteRouteChildren: NovelsRouteRouteChildren = {
  NovelsIndexRoute: NovelsIndexRoute,
}

const NovelsRouteRouteWithChildren = NovelsRouteRoute._addFileChildren(
  NovelsRouteRouteChildren,
)

interface UsersRouteRouteChildren {
  UsersIndexRoute: typeof UsersIndexRoute
}

const UsersRouteRouteChildren: UsersRouteRouteChildren = {
  UsersIndexRoute: UsersIndexRoute,
}

const UsersRouteRouteWithChildren = UsersRouteRoute._addFileChildren(
  UsersRouteRouteChildren,
)

interface NovelsNovelIdChaptersRouteRouteChildren {
  NovelsNovelIdChaptersIndexRoute: typeof NovelsNovelIdChaptersIndexRoute
}

const NovelsNovelIdChaptersRouteRouteChildren: NovelsNovelIdChaptersRouteRouteChildren =
  {
    NovelsNovelIdChaptersIndexRoute: NovelsNovelIdChaptersIndexRoute,
  }

const NovelsNovelIdChaptersRouteRouteWithChildren =
  NovelsNovelIdChaptersRouteRoute._addFileChildren(
    NovelsNovelIdChaptersRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthorsRouteRoute: AuthorsRouteRouteWithChildren,
  NovelsRouteRoute: NovelsRouteRouteWithChildren,
  UsersRouteRoute: UsersRouteRouteWithChildren,
  RateLimitRoute: RateLimitRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthorsCreateRoute: AuthorsCreateRoute,
  NovelsCreateRoute: NovelsCreateRoute,
  NovelsNovelIdChaptersRouteRoute: NovelsNovelIdChaptersRouteRouteWithChildren,
  AuthorsAuthorIdIndexRoute: AuthorsAuthorIdIndexRoute,
  NovelsNovelIdIndexRoute: NovelsNovelIdIndexRoute,
  UsersUsernameIndexRoute: UsersUsernameIndexRoute,
  NovelsNovelIdChaptersCreateRoute: NovelsNovelIdChaptersCreateRoute,
  NovelsNovelIdChaptersChapterIdEditRoute:
    NovelsNovelIdChaptersChapterIdEditRoute,
  NovelsNovelIdChaptersChapterIdIndexRoute:
    NovelsNovelIdChaptersChapterIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
