/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as AboutRouteImport } from './routes/about'
import { Route as NovelsRouteRouteImport } from './routes/novels/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NovelsIndexRouteImport } from './routes/novels/index'
import { Route as NovelsCreateRouteImport } from './routes/novels_/create'
import { Route as NovelsNovelIdIndexRouteImport } from './routes/novels_/$novelId/index'
import { Route as NovelsNovelIdChaptersRouteRouteImport } from './routes/novels_/$novelId/chapters/route'
import { Route as NovelsNovelIdChaptersIndexRouteImport } from './routes/novels_/$novelId/chapters/index'
import { Route as NovelsNovelIdChaptersCreateRouteImport } from './routes/novels_/$novelId/chapters_/create'
import { Route as NovelsNovelIdChaptersChapterIdIndexRouteImport } from './routes/novels_/$novelId/chapters_/$chapterId/index'
import { Route as NovelsNovelIdChaptersChapterIdEditRouteImport } from './routes/novels_/$novelId/chapters_/$chapterId/edit'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const NovelsRouteRoute = NovelsRouteRouteImport.update({
  id: '/novels',
  path: '/novels',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NovelsIndexRoute = NovelsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NovelsRouteRoute,
} as any)
const NovelsCreateRoute = NovelsCreateRouteImport.update({
  id: '/novels_/create',
  path: '/novels/create',
  getParentRoute: () => rootRouteImport,
} as any)
const NovelsNovelIdIndexRoute = NovelsNovelIdIndexRouteImport.update({
  id: '/novels_/$novelId/',
  path: '/novels/$novelId/',
  getParentRoute: () => rootRouteImport,
} as any)
const NovelsNovelIdChaptersRouteRoute =
  NovelsNovelIdChaptersRouteRouteImport.update({
    id: '/novels_/$novelId/chapters',
    path: '/novels/$novelId/chapters',
    getParentRoute: () => rootRouteImport,
  } as any)
const NovelsNovelIdChaptersIndexRoute =
  NovelsNovelIdChaptersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => NovelsNovelIdChaptersRouteRoute,
  } as any)
const NovelsNovelIdChaptersCreateRoute =
  NovelsNovelIdChaptersCreateRouteImport.update({
    id: '/novels_/$novelId/chapters_/create',
    path: '/novels/$novelId/chapters/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const NovelsNovelIdChaptersChapterIdIndexRoute =
  NovelsNovelIdChaptersChapterIdIndexRouteImport.update({
    id: '/novels_/$novelId/chapters_/$chapterId/',
    path: '/novels/$novelId/chapters/$chapterId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const NovelsNovelIdChaptersChapterIdEditRoute =
  NovelsNovelIdChaptersChapterIdEditRouteImport.update({
    id: '/novels_/$novelId/chapters_/$chapterId/edit',
    path: '/novels/$novelId/chapters/$chapterId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/novels': typeof NovelsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/profile': typeof ProfileRoute
  '/novels/create': typeof NovelsCreateRoute
  '/novels/': typeof NovelsIndexRoute
  '/novels/$novelId/chapters': typeof NovelsNovelIdChaptersRouteRouteWithChildren
  '/novels/$novelId/': typeof NovelsNovelIdIndexRoute
  '/novels/$novelId/chapters/create': typeof NovelsNovelIdChaptersCreateRoute
  '/novels/$novelId/chapters/': typeof NovelsNovelIdChaptersIndexRoute
  '/novels/$novelId/chapters/$chapterId/edit': typeof NovelsNovelIdChaptersChapterIdEditRoute
  '/novels/$novelId/chapters/$chapterId/': typeof NovelsNovelIdChaptersChapterIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/profile': typeof ProfileRoute
  '/novels/create': typeof NovelsCreateRoute
  '/novels': typeof NovelsIndexRoute
  '/novels/$novelId': typeof NovelsNovelIdIndexRoute
  '/novels/$novelId/chapters/create': typeof NovelsNovelIdChaptersCreateRoute
  '/novels/$novelId/chapters': typeof NovelsNovelIdChaptersIndexRoute
  '/novels/$novelId/chapters/$chapterId/edit': typeof NovelsNovelIdChaptersChapterIdEditRoute
  '/novels/$novelId/chapters/$chapterId': typeof NovelsNovelIdChaptersChapterIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/novels': typeof NovelsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/profile': typeof ProfileRoute
  '/novels_/create': typeof NovelsCreateRoute
  '/novels/': typeof NovelsIndexRoute
  '/novels_/$novelId/chapters': typeof NovelsNovelIdChaptersRouteRouteWithChildren
  '/novels_/$novelId/': typeof NovelsNovelIdIndexRoute
  '/novels_/$novelId/chapters_/create': typeof NovelsNovelIdChaptersCreateRoute
  '/novels_/$novelId/chapters/': typeof NovelsNovelIdChaptersIndexRoute
  '/novels_/$novelId/chapters_/$chapterId/edit': typeof NovelsNovelIdChaptersChapterIdEditRoute
  '/novels_/$novelId/chapters_/$chapterId/': typeof NovelsNovelIdChaptersChapterIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/novels'
    | '/about'
    | '/profile'
    | '/novels/create'
    | '/novels/'
    | '/novels/$novelId/chapters'
    | '/novels/$novelId/'
    | '/novels/$novelId/chapters/create'
    | '/novels/$novelId/chapters/'
    | '/novels/$novelId/chapters/$chapterId/edit'
    | '/novels/$novelId/chapters/$chapterId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/profile'
    | '/novels/create'
    | '/novels'
    | '/novels/$novelId'
    | '/novels/$novelId/chapters/create'
    | '/novels/$novelId/chapters'
    | '/novels/$novelId/chapters/$chapterId/edit'
    | '/novels/$novelId/chapters/$chapterId'
  id:
    | '__root__'
    | '/'
    | '/novels'
    | '/about'
    | '/profile'
    | '/novels_/create'
    | '/novels/'
    | '/novels_/$novelId/chapters'
    | '/novels_/$novelId/'
    | '/novels_/$novelId/chapters_/create'
    | '/novels_/$novelId/chapters/'
    | '/novels_/$novelId/chapters_/$chapterId/edit'
    | '/novels_/$novelId/chapters_/$chapterId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NovelsRouteRoute: typeof NovelsRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ProfileRoute: typeof ProfileRoute
  NovelsCreateRoute: typeof NovelsCreateRoute
  NovelsNovelIdChaptersRouteRoute: typeof NovelsNovelIdChaptersRouteRouteWithChildren
  NovelsNovelIdIndexRoute: typeof NovelsNovelIdIndexRoute
  NovelsNovelIdChaptersCreateRoute: typeof NovelsNovelIdChaptersCreateRoute
  NovelsNovelIdChaptersChapterIdEditRoute: typeof NovelsNovelIdChaptersChapterIdEditRoute
  NovelsNovelIdChaptersChapterIdIndexRoute: typeof NovelsNovelIdChaptersChapterIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novels': {
      id: '/novels'
      path: '/novels'
      fullPath: '/novels'
      preLoaderRoute: typeof NovelsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novels/': {
      id: '/novels/'
      path: '/'
      fullPath: '/novels/'
      preLoaderRoute: typeof NovelsIndexRouteImport
      parentRoute: typeof NovelsRouteRoute
    }
    '/novels_/create': {
      id: '/novels_/create'
      path: '/novels/create'
      fullPath: '/novels/create'
      preLoaderRoute: typeof NovelsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novels_/$novelId/': {
      id: '/novels_/$novelId/'
      path: '/novels/$novelId'
      fullPath: '/novels/$novelId/'
      preLoaderRoute: typeof NovelsNovelIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novels_/$novelId/chapters': {
      id: '/novels_/$novelId/chapters'
      path: '/novels/$novelId/chapters'
      fullPath: '/novels/$novelId/chapters'
      preLoaderRoute: typeof NovelsNovelIdChaptersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novels_/$novelId/chapters/': {
      id: '/novels_/$novelId/chapters/'
      path: '/'
      fullPath: '/novels/$novelId/chapters/'
      preLoaderRoute: typeof NovelsNovelIdChaptersIndexRouteImport
      parentRoute: typeof NovelsNovelIdChaptersRouteRoute
    }
    '/novels_/$novelId/chapters_/create': {
      id: '/novels_/$novelId/chapters_/create'
      path: '/novels/$novelId/chapters/create'
      fullPath: '/novels/$novelId/chapters/create'
      preLoaderRoute: typeof NovelsNovelIdChaptersCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novels_/$novelId/chapters_/$chapterId/': {
      id: '/novels_/$novelId/chapters_/$chapterId/'
      path: '/novels/$novelId/chapters/$chapterId'
      fullPath: '/novels/$novelId/chapters/$chapterId/'
      preLoaderRoute: typeof NovelsNovelIdChaptersChapterIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novels_/$novelId/chapters_/$chapterId/edit': {
      id: '/novels_/$novelId/chapters_/$chapterId/edit'
      path: '/novels/$novelId/chapters/$chapterId/edit'
      fullPath: '/novels/$novelId/chapters/$chapterId/edit'
      preLoaderRoute: typeof NovelsNovelIdChaptersChapterIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface NovelsRouteRouteChildren {
  NovelsIndexRoute: typeof NovelsIndexRoute
}

const NovelsRouteRouteChildren: NovelsRouteRouteChildren = {
  NovelsIndexRoute: NovelsIndexRoute,
}

const NovelsRouteRouteWithChildren = NovelsRouteRoute._addFileChildren(
  NovelsRouteRouteChildren,
)

interface NovelsNovelIdChaptersRouteRouteChildren {
  NovelsNovelIdChaptersIndexRoute: typeof NovelsNovelIdChaptersIndexRoute
}

const NovelsNovelIdChaptersRouteRouteChildren: NovelsNovelIdChaptersRouteRouteChildren =
  {
    NovelsNovelIdChaptersIndexRoute: NovelsNovelIdChaptersIndexRoute,
  }

const NovelsNovelIdChaptersRouteRouteWithChildren =
  NovelsNovelIdChaptersRouteRoute._addFileChildren(
    NovelsNovelIdChaptersRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NovelsRouteRoute: NovelsRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ProfileRoute: ProfileRoute,
  NovelsCreateRoute: NovelsCreateRoute,
  NovelsNovelIdChaptersRouteRoute: NovelsNovelIdChaptersRouteRouteWithChildren,
  NovelsNovelIdIndexRoute: NovelsNovelIdIndexRoute,
  NovelsNovelIdChaptersCreateRoute: NovelsNovelIdChaptersCreateRoute,
  NovelsNovelIdChaptersChapterIdEditRoute:
    NovelsNovelIdChaptersChapterIdEditRoute,
  NovelsNovelIdChaptersChapterIdIndexRoute:
    NovelsNovelIdChaptersChapterIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
